# Generated by Django 4.1.1 on 2022-10-04 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_tailor', '0002_participant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Profile',
        ),
    ]
