# Generated by Django 4.1.1 on 2022-10-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_tailor', '0003_rename_participant_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentrtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('abbr', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Hard', 'Hard'), ('Soft', 'Soft')], max_length=4)),
                ('feild', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_tailor.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_tailor.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_tailor.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_tailor.profile')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('unigrams', models.TextField()),
                ('bigrams', models.TextField()),
                ('trigrams', models.TextField()),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume_tailor.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume_tailor.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('label', models.CharField(choices=[('Work', 'Work'), ('Leadership', 'Leadership')], max_length=20)),
                ('on_current', models.BooleanField(default=True)),
                ('loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume_tailor.location')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_tailor.organization')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_tailor.position')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_date', models.DateField()),
                ('consentration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_tailor.consentrtion')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_tailor.degree')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_tailor.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('Work', 'Work'), ('Summary', 'Summary')], max_length=20)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_tailor.experience')),
            ],
        ),
    ]
