# Generated by Django 4.1.1 on 2022-10-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_tailor', '0004_consentrtion_degree_organization_position_skill_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consentrtion',
            new_name='Consentration',
        ),
    ]
