# Generated by Django 4.1.1 on 2022-11-14 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_tailor', '0009_alter_resumeupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
